### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by bigdaas** [bigdaas/TCEC-gui-issues#1]
10:19:02 AM

110875035 AllieStein v0.5-dev_1359f44-n8(123): stop

**Comment by bigdaas** [comment]
From the GUI livelogs:


10:19:23 AM

110893994 AllieStein v0.5-dev_1359f44-n8(123): FATAL ERROR: Network error: Software caused connection abort
Terminating process of engine AllieStein v0.5-dev_1359f44-n8(123)
110895038 Stockfish 19061419(122): quit
10:19:30 AM

12 Laser 230319 -120 127 9 33.3% 66.7%
13 Fizbo 2 -166 156 9 27.8% 55.6%
14 Andscacs 0.95123 -166 156 9 27.8% 55.6%
Finished match
Finished game 303 (Stockfish 19061419 vs AllieStein v0.5-dev_1359f44-n8): 1-0 {Black disconnects}

**Comment by bigdaas** [comment]
the legacy site (http://legacy-tcec.chessdom.com/live.php) appears to indicate the same issue, and both live & legacy sites now seem to be frozen—without any activity—except for the chat windows which seem to be functional.

**Comment by Aloril** [comment]
Just usual network disconnection, fix is either
1) one machine solution
2) write wrapper server script for GPU machine that adds timestamps and can kill stuck engines and notice when engine crashes and modify cutechess-cli to support this.
