### ISSUE TITLE
Time wrong

### ISSUE THREAD

**Issue by Dorus** [bigdaas/TCEC-gui-issues#5]
Schedule say last game started on 03:27:20 on 2019.07.04, while it actually begun like 20:25:00 on 2019.07.03. I'm in GMT+1 (GMT+2 in Daylight saving time actually) timezone.

**Comment by bigdaas** [comment]
the dates & times used to be displayed as local time, but now it appears to be several more hours ahead of the actual schedule.  

coordinating with Aloril and Kan

**Comment by Dorus** [comment]
I forgot to add i use https://tcecbeta.club/live.html because the main site is a huge mess (caching problem, so i have no schedule at all).

**Comment by bigdaas** [comment]
time appears to be local time +7 hours

**Comment by bigdaas** [comment]
issue appears to have resolved itself

**Comment by Dorus** [comment]
Can confirm
