### ISSUE TITLE
(almost) empty gray area below top menu is wasting screen space

### ISSUE THREAD

**Issue by Matthies** [bigdaas/TCEC-gui-issues#9]
The area with the three (small) icons TCEC, chessdom, paypal is way too large (compared to the icons) and wasting screen space. Using Chrome browser on Windows 10.

**Comment by m-yosefpor** [comment]
![Screenshot from 2019-09-17 17-43-33](https://user-images.githubusercontent.com/47300215/65044740-c40a0180-d972-11e9-9271-43785bc0b7a4.png)

same problem here.. both on Ubuntu and Android

**Comment by Matthies** [comment]
Area for (at that time missing) adverts.
